vich_uploader:
    db_driver: orm

    mappings:
       category_images:
           uri_prefix: /uploads/category
           upload_destination: '%kernel.project_dir%/public/uploads/category'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
